# Route Project Makefile for building the paper and src subprojects, ensuring
# the stage, data, and build directories exist, and promoting the final PDF to
# the stage directory after building the subprojects. Data generated through 
# the subprojects is stored in the data directory, and intermediate build files 
# are stored in the build directory. The clean target removes all generated 
# files and directories to ensure a clean build environment.
#------------------------------------------------------------------------------
# flags passed to the make command:
#   -j: Run multiple jobs in parallel to speed up the build process. The number
#	    of jobs can be specified after the -j flag (e.g., -j4 to run 4 jobs in
#	    parallel). If no number is specified, make will run as many jobs as there
#	    are available on the system. Running in parallel can significantly reduce 
#	    the time it takes to run experiments.
#   experiment="<exp_name1 exp_name2 ...>": Run a specific experiment defined 
#       or a list of experiment in the experiments subproject.
#		This can be used to run a single experiment without running 
#		the entire audit target, which can save time when iterating on a 
#		experiment. The experiment name should match the name of the target 
#		defined in the src/experiments/makefile. Please see the file 
#		src/experiments/makefile for the list of experiments and their 
#		corresponding targets. Some experiments may take a day or more to run
#       on a lapetop, so it is recommended to run long experiments on a server 
#		for cluster with more resources, and to use the experiment=<exp_name> 
#		flag to run specific experiments as needed.
#   experiment=all: Run all experiments defined in the src subproject. This can 
#		be used to run all experiments without specifying each one individually.
#       It is recommended to run this with -j or it could take a week to get
# 	    through all experiments on a laptop, and to run on a server or cluster.
#------------------------------------------------------------------------------
# targets:
#   all: The default target, which builds the setup, env, tests, clean, paper, 
#        andexperiments, audit, and promote targets.
#   info: prints information about the project at each subproject level.
#   env: Sets up the virtual environment for the project, ensuring the virtual
#        environment is created and dependencies are installed before running
#        tests. The requirements.txt file is kept up to date with the python
#        dependencies for the project, and is used to install dependencies in 
#        the virtual environment.
#   audit: checks and prints the results of the tests and experiments to make 
#        sure they have run and "PASSED" before allowing the build to complete.
#        Running the audit will tell you which tests or experiments nee to run.
#   tests: Runs tests defined in the tests subproject, ensuring the virtual 
#		 environment is set up before running
#        Requires: setup env
#   experiments: Runs experiments defined by the exeperiment macro on the
#        command line. This target can run for a week or more on a laptop
#        if exp_all is specified.
#   setup: Sets up the environment for the project, ensuring the stage, data, 
#        and build directories exist before building. 
#		 Requires: env
#   clean_env: Cleans the virtual environment by removing the virtual environment
#        directory and any .pyc files or __pycache__ directories. This target is		useful for ensuring a clean environment when building the project, especially 
#        if there are issues with the virtual environment or dependencies. It is 
#        recommended to run this target before building the project if there are 
#        issues with the virtual environment or dependencies.
#   clean: removes the build and stage directories which effect only the files 
#        created by Lattex commands and will cause the paper to rebuild. 
#        Experiments are not cleaned by this target since they can take a long 
#        time to run, and it is not necessary to clean them when rebuilding the 
#        paper although they do produce data files used to make figures. The 
#        paper target will be rebuilt if they were deleted, but this should not 
#        happen if the makefile is used correctly because those files are 
#        tracked by version control and created by the experiments and utilities. 
#        All of the files can be created by the build process but not cleaned.
#   promote: Promotes the final PDF and other figures and documentsto the stage 
#        directory after building the subprojects.
#   clean: Cleans all generated files and directories to ensure a clean build environment
#------------------------------------------------------------------------------
# subprojects:
#   data: Contains experimental data files generated by running experiments
#        or utilities. 
#   figures: Contains figure files some static and others generated 
#        through the build process.
#   paper: Builds the paper PDF using pdflatex, ensuring the build directory 
#        exists before building
#   src: Builds data files needed for the paper, ensuring 
#        the data and build directories exist before building build directories 
#        exist before building
#   tests: Builds any tests for the project, ensuring the virtual environment 
#        is set up before building
#------------------------------------------------------------------------------
# directories:
#   figures: Directory for storing any figures generated through the build 
#       process, used in the paper. Figure files are excluded from version 
#		control and are generated through the build process. This directory is 
#		source controlled since it may contain manually curated figure files 
#       that are used in the paper, and of use for future research by others.
#   paper: Directory for storing the .tex files for the paper. The paper PDF
#       will be found in the build directory and moved to the stage directory
#       if the audit passes and the build is successful.
#   src Directory for storing source code for the project, such as scripts for
#       generating data, figures, and tables for the paper. Source files are 
#       source controlled and may be generated through the build process.
#   stage: Directory for staging the final PDF before creating a release in 
#		GitHub PDF files are excluded from version control and are generated 
#       through the build process
#   tests: Directory for storing any test files for the project, such as unit 
#       and integration tests. Test files are source controlled and may be 
#       generated through the build process.
#   data: Directory for storing any data files generated through by the 
#       subprojects, used to create figures or tables in the paper. Data files 
#       are excluded from version control and are generated through the build 
#		process. These data directory is source controlled since it may contain 
#       manually curated data files that are used in the paper, and of use
#       for future research by others.
#   build: Directory for storing any intermediate build files generated through 
#       the subprojects, such as .aux, .log, .out, .toc, .lof, and .lot files 
#       generated by pdflatex. These build files are excluded from version 
#       control and are generated through the build process. Test results are 
#       also stored in the build directory, and are excluded from version 
#		control and generated through the build process.
#------------------------------------------------------------------------------
# Files related to builds in the project root:
#   makefile: This file.
#   targets.mak: Makefile for inclusions by all makefiles in the project
#   common.mak: Makefile for defining common variables and targets for all
#               makefiles in the project.
#   subproject.mak: Makefile for defining common variables and targets for all
#               subprojects in the project. Includes the common makefile.
#   setup.cmd: Windows batch file for setting up the environment for the project
#   setup.sh: Unix shell script for setting up the environment for the project

#------------------------------------------------------------------------------
# Note: The final PDF is promoted to the stage directory after building the subprojects, to the stage
#       directory to ensure it is not accidentally committed to version control and to facilitate
#       creating a release in GitHub. The stage directory is excluded from version control and is
#       generated through the build process. Also raw figures and charts used in the paper may
#       may be promoted to the state directory for use by others, and in presentations so that they
#       are included in the release of the paper on GitHub, but these are not all generated through 
#       the build process and are source controlled.
#------------------------------------------------------------------------------
# Setup the virtual environment for the project
# Each makefile has a relative path to the project root, so we can define the 
# location of the virtual environment and other directories relative to the 
# project root.
RELATIVE_PATH :=
include common.mak

SUBPROJECTS := paper src tests data figures

# Definephony targets for testing, running experiments, cleaning, building LaTeX, 
# and promoting.
# Each subproject must have the following audit targets defined, stubs for these
# are okay.
AUDIT_SUBPROJECTS = $(SUBPROJECTS:%=audit-%)
CLEAN_SUBPROJECTS = $(SUBPROJECTS:%=clean-%)
DATA_SUBPROJECTS = $(SUBPROJECTS:%=data-%)
FIGURES_SUBPROJECTS = $(SUBPROJECTS:%=figures-%)
EXPERIMENTS_SUBPROJECTS = $(SUBPROJECTS:%=experiments-%)
PAPER_SUBPROJECTS = $(SUBPROJECTS:%=paper-%)
PROMOTE_SUBPROJECTS = $(SUBPROJECTS:%=promote-%)
TEST_SUBPROJECTS = $(SUBPROJECTS:%=test-%)

# The name of the file for input to pip install for setting up the virtual 
# environment.
local_requirements := requirements.txt
source_requirements := $(subst \,/,$(USERPROFILE))/requirements.txt

# Define the .PHONY target to include all, clean, subprojects, and directories
.PHONY: all setup clean tests info \
        promote paper experiments clean_env audit $(CLEAN_SUBPROJECTS) \
		$(EXPERIMENTS_SUBPROJECTS) $(AUDIT_SUBPROJECTS) \
		$(PROMOTE_SUBPROJECTS) $(PAPER_SUBPROJECTS) $(TEST_SUBPROJECTS)

# Define the all target to depend on cleaning, assembling, and promoting
all: setup clean tests audit assemble promote
	@echo "================ Build Complete ================"

start: setup
	@echo "================ Starting Build ================"

requirements.txt: $(source_requirements)
	@echo "============ Copying requirements.txt ============"
	cp -vf $< $@

# Create the virtual environment and install dependencies
# The 'touch' command ensures Make knows when the environment was last updated
$(VENV):
	@echo "============ Setting up virtual environment ============"
	python -m venv $(VENV)

$(VENV)/touchfile: $(VENV) requirements.txt
	@echo "========= Setup Installing dependencies ==============="
	$(PYTHON) -m pip install --upgrade pip
	$(PIP) install -r requirements.txt
	touch $(VENV)/touchfile

tests: $(VENV)/touchfile
	@echo "================ Running Tests ================"
	$(MAKE) -C tests test

# The assemble target depends on building each subproject in order, 
# ensuring the stage, data, and build directories exist before building 
# each subproject
paper: $(PAPER_SUBPROJECTS)
	@echo "================ Paper Complete ================"

# Build each subproject in order
$(PAPER_SUBPROJECTS):
	@echo "============ Assembling $(@:paper-%=%) ============"
	$(MAKE) -C $(@:paper-%=%) assemble	

# The promote target depends on the final PDF being built in the paper subdir 
# and then copies it to the stage directory
promote: $(PROMOTE_SUBPROJECTS)
	@echo "================ Promote Complete ================"

# Ensure the final PDF is promoted to the stage directory after building 
#the subprojects
$(PROMOTE_SUBPROJECTS):
	@echo "============ Promoting $(@:promote-%=%) ============"
	$(MAKE) -C $(@:promote-%=%) promote

# Alias for setting up the environment
setup: env $(stage_dir) $(data_dir) $(build_dir)
	@echo "================ Setup Complete ================"

env: $(VENV)/touchfile requirements.txt
	@echo "================ env Complete ================"

# Local clean target that depends on cleaning each subdir
clean: $(CLEAN_SUBPROJECTS)
	-rm -rfv $(stage_dir) $(build_dir)
	@echo "================ Clean Complete ================"

# Define a pattern rule for cleaning each subdir
$(CLEAN_SUBPROJECTS):
	@echo "============ Cleaning $(@:clean-%=%) ============"
	$(MAKE) -C $(@:clean-%=%) clean

# Define the audit target to run all experiments or scripts 
# defined in the src subproject and generate a report
audit: $(AUDIT_SUBPROJECTS) $(data_dir)/audit_report.txt

$(data_dir)/audit_report.txt: audit_universe.py $(VENV)/touchfile src/experiments/*.py
	@echo "============ Auditing src ============"
	$(PYTHON) audit_universe.py | $(TEE) -i $(data_dir)/audit_report.txt

# Define a pattern rule for auditing each subdir
$(AUDIT_SUBPROJECTS):
	@echo "============ Auditing $(@:audit-%=%) ============"
	$(MAKE) -C $(@:audit-%=%) audit

include $(RELATIVE_PATH)targets.mak