# Makefile for building the paper and src subprojects, ensuring the stage, 
# data, and build directories exist, and promoting the final PDF to the stage 
# directory after building the subprojects. Data generated through the 
# subprojects is stored in the data directory, and intermediate build files are stored
# in the build directory. The clean target removes all generated files and
# directories to ensure a clean build environment.
#
# targets:
#   all: Cleans, assembles, and promotes the final PDF to the stage directory
#   assemble: Builds each subproject in order, ensuring the stage, data, and build directories 
#             exist before building each subproject.
#   promote: Promotes the final PDF and other figures and documentsto the stage directory 
#            after building the subprojects.
#   clean: Cleans all generated files and directories to ensure a clean build environment
#   run: Runs experiments or scripts defined in the src subproject, ensuring the data 
#        directory exists before running and creating any data files of use to creating
#        figures or tables in the paper.
#   audit: Runs all experiments or scripts defined in the src subproject and generates a report
# subprojects:
#   paper: Builds the paper PDF using pdflatex, ensuring the build directory exists before building
#   src: Builds any source code or data files needed for the paper, ensuring the data and 
#        build directories exist before building
# directories:
#   stage: Directory for staging the final PDF before creating a release in GitHub
#          PDF files are excluded from version control and are generated through the build process
#   data: Directory for storing any data files generated through by the subprojects, used to create 
#         figures or tables in the paper. Data files are excluded from version control and are 
#         generated through the build process. These data directory is source controlled since
#    	  it may contain manually curated data files that are used in the paper, and of use
#         for future research by others.
#   build: Directory for storing any intermediate build files generated through by the subprojects,
#          such as .aux, .log, .out, .toc, .lof, and .lot files generated by pdflatex. These build
#          files are excluded from version control and are generated through the build process.
# Note: The final PDF is promoted to the stage directory after building the subprojects, to the stage
#       directory to ensure it is not accidentally committed to version control and to facilitate
#       creating a release in GitHub. The stage directory is excluded from version control and is
#       generated through the build process. Also raw figures and charts used in the paper may
#       may be promoted to the state directory for use by others, and in presentations so that they
#       are included in the release of the paper on GitHub, but these are not all generated through 
#       the build process and are source controlled.

# Setup the virtual environment for the project
RELATIVE_PATH :=
include $(RELATIVE_PATH)common.mak

SUBPROJECTS := paper src

# Definephony targets for cleaning, assembling, and promoting each subdir
CLEAN_SUBPROJECTS = $(SUBPROJECTS:%=clean-%)
ASSEMBLE_SUBPROJECTS = $(SUBPROJECTS:%=assemble-%)
PROMOTE_SUBPROJECTS = $(SUBPROJECTS:%=promote-%)
AUDIT_SUBPROJECTS = $(SUBPROJECTS:%=audit-%)

local_requirements := requirements.txt
source_requirements := $(subst \,/,$(USERPROFILE))/requirements.txt
requirements_different := $(shell cmp -s $(local_requirements) $(source_requirements) || echo "yes")
ifeq ($(requirements_different), "yes")
		$(shell cp -vf $(source_requirements) $(local_requirements))
endif

# Define the .PHONY target to include all, clean, subprojects, and directories
.PHONY: all start setup clean \
        promote assemble audit $(CLEAN_SUBPROJECTS) $(ASSEMBLE_SUBPROJECTS) \
		$(PROMOTE_SUBPROJECTS) $(AUDIT_SUBPROJECTS)

# Define the all target to depend on cleaning, assembling, and promoting
all: start setup audit assemble promote
	@echo "================ Build Complete ================"

start: requirements.txt
	@echo "================ Starting Build ================"

requirements.txt: 
	@echo "================ Checking requirements ================"
	@echo "No additional requirements needed for this project" > requirements.txt

# Create the virtual environment and install dependencies
# The 'touch' command ensures Make knows when the environment was last updated
$(VENV):
	@echo "============ Setting up virtual environment ============"
	python -m venv $(VENV)

$(VENV)/touchfile: $(VENV) requirements.txt
	@echo "========= Setup Installing dependencies ==============="
	$(PYTHON) -m pip install --upgrade pip
	$(PIP) install -r requirements.txt
	touch $(VENV)/touchfile

# The assemble target depends on building each subproject in order, 
# ensuring the stage, data, and build directories exist before building 
# each subproject
assemble: $(ASSEMBLE_SUBPROJECTS)
	@echo "================ Assemble Complete ================"

# Build each subproject in order
$(ASSEMBLE_SUBPROJECTS):
	@echo "============ Assembling $(@:assemble-%=%) ============"
	$(MAKE) -C $(@:assemble-%=%) assemble	

# The promote target depends on the final PDF being built in the paper subdir 
# and then copies it to the stage directory
promote: $(PROMOTE_SUBPROJECTS)
	@echo "================ Promote Complete ================"

# Ensure the final PDF is promoted to the stage directory after building 
#the subprojects
$(PROMOTE_SUBPROJECTS):
	@echo "============ Promoting $(@:promote-%=%) ============"
	$(MAKE) -C $(@:promote-%=%) promote

# Alias for setting up the environment
setup: $(VENV)/touchfile $(stage_dir) $(data_dir) $(build_dir)
	@echo "================ Setup Complete ================"

# Example of a test target using pytest
test:
#	$(VENV)/bin/pytest tests/

clean_env: 
	@echo "============ Cleaning virtual environment ============"
	-rm -rfv $(VENV)
	-find . -type f -name '*.pyc' -delete
	-find . -type d -name '__pycache__' -exec rm -rf {} +
	@echo "================ Clean_env Complete ================"

# Local clean target that depends on cleaning each subdir
clean: $(CLEAN_SUBPROJECTS)
	-rm -rfv $(stage_dir) $(build_dir)
	@echo "================ Clean Complete ================"

# Define a pattern rule for cleaning each subdir
$(CLEAN_SUBPROJECTS):
	@echo "============ Cleaning $(@:clean-%=%) ============"
	$(MAKE) -C $(@:clean-%=%) clean

# Define the audit target to run all experiments or scripts 
# defined in the src subproject and generate a report
audit: $(AUDIT_SUBPROJECTS) $(data_dir)/audit_report.txt

$(data_dir)/audit_report.txt: audit_universe.py $(VENV)/touchfile src/experiments/*.py
	@echo "============ Auditing src ============"
	$(PYTHON) audit_universe.py | $(TEE) -i $(data_dir)/audit_report.txt

# Define a pattern rule for auditing each subdir
$(AUDIT_SUBPROJECTS):
	@echo "============ Auditing $(@:audit-%=%) ============"
	$(MAKE) -C $(@:audit-%=%) audit

include $(RELATIVE_PATH)targets.mak