"""
automorphism_rgb_su3.py

Step 5 sub-step: map the framework's existing RGB symmetry into U(3)
and see how much of SU(3) it covers.

The conjecture (notes/lie_algebra_automorphism_proof_sketch.md) needs
SU(3) (dim 8) acting on a C^3 internal index of the framework.  The
question this script answers:

  Is SU(3) generated by the framework's existing discrete RGB
  symmetry, or does it require an additional structural input?

Analysis path:

1. The discrete spatial symmetry of (Gamma, V) was shown by
   automorphism_discrete.py to be a 48-element group (B_3) with a
   12-element orthogonal subgroup S_3 x C_2 -- the RGB-permutation
   action plus bipartite parity.

2. The 6 permutations of {V_1, V_2, V_3} embed in U(3) as 6 specific
   3x3 unitary matrices on the C^3 weight space (alpha_1, alpha_2,
   alpha_3) of the kinetic-step weights.

3. Within SU(3) (after fixing det = +1), the embedding gives only the
   3 even permutations -- the cyclic group A_3 = Z_3.  The 3 odd
   permutations (transpositions) have det = -1 and lie in U(3) but
   not SU(3).

4. Z_3 is a finite discrete subgroup of SU(3) and does NOT generate
   any continuous SU(3) subgroup as a topological closure.

5. Therefore the SU(3) factor in the automorphism conjecture cannot
   be a continuous extension of the framework's existing finite RGB
   symmetry.  It must come from somewhere else.

The script verifies steps 2-4 explicitly using sympy and reports the
gap.

Conclusion: SU(3) is a structural ADDITION to the framework, not a
direct continuation of its discrete RGB symmetry.  The natural
candidate (made explicit in the proof-sketch update) is a per-site
"color memory" -- which of (V_1, V_2, V_3) was traversed most
recently -- enriching the per-site amplitude from C^2 to C^2 (x) C^3.
"""

import itertools
import numpy as np
import sympy as sp
from sympy import I, sqrt, Matrix, eye, simplify, conjugate, Rational


def s3_embedding_in_u3():
    """The 6 permutation matrices of S_3 embedded in U(3).

    Each permutation sigma in S_3 corresponds to the matrix P_sigma
    with P_sigma[i, j] = 1 if i = sigma(j), else 0.  These act on
    column vectors (alpha_1, alpha_2, alpha_3)^T by permuting entries.
    """
    perms = list(itertools.permutations([0, 1, 2]))
    matrices = []
    for sigma in perms:
        P = sp.zeros(3, 3)
        for j in range(3):
            P[sigma[j], j] = 1
        matrices.append((sigma, P))
    return matrices


def verify_unitarity_and_dets(matrices):
    """For each P, verify P^* P = I and report det(P)."""
    results = []
    for sigma, P in matrices:
        P_dag = P.H
        is_unitary = (P_dag @ P).equals(eye(3))
        d = P.det()
        results.append((sigma, P, is_unitary, d))
    return results


def in_su3(d):
    """Whether det = +1 (i.e., the matrix is in SU(3))."""
    return d == 1


def commutator(A, B):
    """Lie bracket [A, B] = A B - B A."""
    return A @ B - B @ A


def closure_attempt(matrices, max_steps=3):
    """Try to close the set of matrices under multiplication and report
    whether the result is a finite group or extends continuously.
    For finite discrete sets, multiplication closes after finitely many
    rounds; for sets generating a Lie subgroup, there is no finite
    closure.  We just verify the closure size doesn't grow indefinitely.
    """
    current = {tuple(M.flat()) for _, M in matrices}
    for step in range(max_steps):
        new = set()
        for k1 in current:
            M1 = sp.Matrix(3, 3, lambda i, j: k1[3*i + j])
            for k2 in current:
                M2 = sp.Matrix(3, 3, lambda i, j: k2[3*i + j])
                P = M1 @ M2
                new.add(tuple(P.flat()))
        if new <= current:
            return len(current), True
        current |= new
    return len(current), False


def lie_algebra_check(matrices_in_su3):
    """For matrices in SU(3), check whether their commutators yield
    new matrices (suggesting a continuous extension) or stay within
    the discrete set."""
    new_elements = []
    sigs = {tuple(simplify(M).flat()) for _, M in matrices_in_su3}
    for (s1, M1), (s2, M2) in itertools.combinations(matrices_in_su3, 2):
        C = simplify(commutator(M1, M2))
        sig = tuple(C.flat())
        if sig not in sigs:
            # Check if the commutator is just a scalar multiple of an
            # existing element or genuinely new
            new_elements.append((s1, s2, C))
    return new_elements


def report():
    print("=" * 70)
    print("RGB symmetry embedded in U(3) and the gap to SU(3)")
    print("=" * 70)
    print()

    # Step 1: The 6 permutation matrices of S_3 in U(3)
    matrices = s3_embedding_in_u3()
    results = verify_unitarity_and_dets(matrices)

    print("S_3 -> U(3): 6 permutation matrices")
    print("-" * 70)
    print(f"{'sigma':<14} {'unitary':<10} {'det':<8} {'in SU(3)?'}")
    print("-" * 70)

    in_su3_matrices = []
    not_in_su3_matrices = []
    for sigma, P, is_u, d in results:
        in_su3_flag = in_su3(d)
        print(f"{str(sigma):<14} {str(is_u):<10} {str(d):<8} {in_su3_flag}")
        if in_su3_flag:
            in_su3_matrices.append((sigma, P))
        else:
            not_in_su3_matrices.append((sigma, P))

    print()
    print(f"Total in SU(3) (det = +1): {len(in_su3_matrices)}")
    print(f"In U(3) but not SU(3) (det = -1): {len(not_in_su3_matrices)}")
    print()

    # Step 2: identify the SU(3) part as Z_3 = A_3
    print("-" * 70)
    print("The SU(3) part: Z_3 = A_3 (alternating group on 3 elements)")
    print("-" * 70)
    print("The 3 even permutations form a cyclic subgroup of order 3:")
    print()
    for sigma, P in in_su3_matrices:
        print(f"  sigma = {sigma}:")
        sp.pprint(P)
        print()

    # Verify Z_3 structure: P^3 = I for each non-identity element
    print("Z_3 structure check:")
    for sigma, P in in_su3_matrices:
        P_cubed = P @ P @ P
        is_cube_identity = P_cubed.equals(eye(3))
        print(f"  {sigma}: P^3 = I? {is_cube_identity}")
    print()

    # Step 3: closure of the SU(3) embedding under multiplication
    print("-" * 70)
    print("Closure under multiplication")
    print("-" * 70)
    size, closed = closure_attempt(in_su3_matrices)
    print(f"Set size after multiplication-closure: {size}")
    print(f"Closed under multiplication: {closed}")
    print()
    print("Result: the embedding gives a finite discrete subgroup of")
    print("SU(3), specifically Z_3.  This is NOT a continuous Lie")
    print("subgroup -- discrete groups don't generate continuous")
    print("Lie groups by closure alone.")
    print()

    # Step 4: Lie-algebra check via commutators
    print("-" * 70)
    print("Lie-algebra check: commutators of the embedded elements")
    print("-" * 70)
    new = lie_algebra_check(in_su3_matrices)
    print(f"Number of commutators producing new elements: {len(new)}")
    if new:
        print("Sample new commutator:")
        s1, s2, C = new[0]
        print(f"  [{s1}, {s2}] =")
        sp.pprint(C)
    print()

    if len(new) > 0:
        print("Note: even with new commutator elements, the generated set")
        print("remains finite (Z_3 is closed under [a, b] = ab - ba in")
        print("the abelian sense -- all commutators vanish or land back")
        print("in Z_3).  This is the key obstruction: an abelian group")
        print("cannot generate a non-abelian Lie algebra.")

    print()

    # Step 5: dimension count summary
    print("-" * 70)
    print("Dimension count for the conjecture")
    print("-" * 70)
    print()
    print("Conjecture: Aut(T_diamond, A=1) = SO(3,1) x SU(3) x SU(2) x U(1)")
    print("Total dim: 6 + 8 + 3 + 1 = 18")
    print()
    print("What is established:")
    print("  Spatial S_3 x C_2 -> SO(3) (continuum, dim 3)")
    print("  Boost extension via O_h-averaging (paper sec 6) -> +3 (boosts)")
    print("  Per-site SU(2) (Dirac spinor) -> dim 3")
    print("  Per-site U(1) (phase oscillator) -> dim 1")
    print("  Subtotal: 3 + 3 + 3 + 1 = 10")
    print()
    print("What is open: SU(3) (dim 8).")
    print()
    print("The framework's existing discrete RGB symmetry (S_3) embeds")
    print("in U(3) but only Z_3 = A_3 lies in SU(3).  Z_3 is abelian and")
    print("does NOT generate the non-abelian SU(3) (dim 8) by any natural")
    print("Lie-theoretic operation (closure, commutators, exponentiation).")
    print()
    print("Conclusion: SU(3) is a structural ADDITION, not a continuation")
    print("of the framework's existing RGB symmetry.  The conjecture")
    print("requires identifying the additional structure that supports")
    print("SU(3); see proof-sketch note Step 5 update for the candidate")
    print("mechanism (per-site C^3 'color memory' of recent basis-vector")
    print("traversal).")


if __name__ == '__main__':
    report()
